### ISSUE TITLE
Card number not loaded when click on cover image

### ISSUE THREAD

**Issue by tjanssens** [dewyze/trello-card-numbers#1]
The card number does not show in the card detail when you click on the cover image.

Solution:
Add the same event listener on $("div.list-card-cover.js-card-cover") as on https://github.com/dewyze/trello-card-numbers/blob/master/trello-card-numbers.js#L81

**Comment by dewyze** [comment]
I made some updates to fix that. It's possible that the updates haven't pushed yet. Can you try updating the extension and let me know if it's fixed?

**Comment by dewyze** [comment]
@tjanssens Added another update today, does this fix the issues you were having? (You may need to force update to get it right away).

**Comment by dewyze** [comment]
I believe this is fixed, feel free to reopen if it is not.
