### ISSUE TITLE
card count in right upper corner

### ISSUE THREAD

**Issue by paulvi** [dewyze/trello-card-numbers#15]
Move card count into right upper corner, without adding extra line, as currently page blinks and shift done as the plugin updates page

Actually it was so before

![image](https://cloud.githubusercontent.com/assets/1614482/21762005/556bf968-d691-11e6-92b1-597ac34a3037.png)

but now

![image](https://cloud.githubusercontent.com/assets/1614482/21762027/79151912-d691-11e6-93d3-29ae788842c4.png)

**Comment by dewyze** [comment]
Will look into this

**Comment by paulvi** [comment]
I found a solution by installing "CardCounter for Trello" https://chrome.google.com/webstore/detail/cardcounter-for-trello/miejdnaildjcmahbhmfngfdoficmkdhi

I works well, but with the plugin installed, now I'd like to hide/remove card count done by this plugin

**Comment by dewyze** [comment]
I am going to close this issue. If you want to add a PR for removing card count as an option I'd happily consider it.
