### ISSUE TITLE
suggestion - add id to search results

### ISSUE THREAD

**Issue by antulik** [dewyze/trello-card-numbers#2]
trello can search by id, would be nice to include ID in the title there as well

![image](https://cloud.githubusercontent.com/assets/831942/6445800/858c5336-c117-11e4-9ab5-1e7833a2e4d8.png)

**Comment by dewyze** [comment]
To be clear, you mean just add the number of the card in the display results? So in your picture, `Trademark check` would say `#34 Trademark Check`?

**Comment by antulik** [comment]
@dewyze yes, that's exactly what I mean

**Comment by dewyze** [comment]
I will look into this over the weekend, thanks!

**Comment by dewyze** [comment]
I have been working on this and will likely add it in soon. I am trying to make a pure javascript version (not that the load time is huge, but if I can eliminate jQuery it would be nice). I will add it in with that.

**Comment by dewyze** [comment]
This has been completed here:https://github.com/dewyze/trello-card-numbers/commit/d3b05efe7944fbf2472076b1f9077dc2cc290de7

![screenshot 2015-03-18 10 09 25](https://cloud.githubusercontent.com/assets/1312168/6711754/e3bb3e72-cd56-11e4-8ee3-7cae3f4de74c.png)

**Comment by antulik** [comment]
awesome 👍
