### ISSUE TITLE
Safari port

### ISSUE THREAD

**Issue by ytn3rd** [dewyze/trello-card-numbers#20]
I made a port of this library for Safari (required little to no effort, thanks for your hard work though). Would it be ok to update your main ReadMe to link to the [Safari port](https://github.com/FourPi/trello-card-numbers-safari) somewhere?

**Comment by dewyze** [comment]
Totally, just add it to the Readme and pull request it.

**Comment by ytn3rd** [comment]
Added in with my other PRs in #19. Will close this and continue comments there. If you are happy with those changes getting an update to the store when you're free would be good so I don't get the "Unsupported Extensions Disabled" message because its not signed correctly.
