### ISSUE TITLE
suggestion - highlight id in bold

### ISSUE THREAD

**Issue by antulik** [dewyze/trello-card-numbers#3]
right now id has the same font as the title, which makes it hard to visually separate. I'd like to suggest and make ID text bold, which should help to visually distinguish 'id' from 'title'.

![image](https://cloud.githubusercontent.com/assets/831942/6462592/7d136268-c1bb-11e4-938e-b4607cc8feb5.png)

**Comment by dewyze** [comment]
I will look into this over the weekend, thanks!

**Comment by dewyze** [comment]
I have decided I do not want this to be an automatic feature, many people I asked would find it more obnoxious than helpful.

However, I was debating adding this (and maybe a few other nifty features) using an options page. Would that be useful or destroy the simplicity/ease of this extension for you and others who share your workflow?

**Comment by antulik** [comment]
I think options page is the optimal solution here (without button, but with link in extensions list). Simplicity won't change as the default behaviour would remain the same

**Comment by dewyze** [comment]
@antulik Would be willing to check out the `options_page` branch and install it locally and give me your thoughts?

There are 3 new features:
1. Bold ids
2. Color ids
3. Right click context menu can copy the card id (i.e. `UC32foe`)

**Comment by dewyze** [comment]
Having a context menu dependent on an option seems to be causing some strange side effects, at least when using a background/event page. You can change the option, and reload the page and nothing works. However, if you change the option, reload the extension and then just go to the page, the menu is now available. I am not sure I will keep that functionality.

**Comment by dewyze** [comment]
Removed the copy card id context menu for now. May add later in a separate PR.

**Comment by antulik** [comment]
@dewyze  looked at the branch

- options menu need some love with styles
- bug: background color of text box is not loaded when opening options 
- each color change requires trello page reload, (not ideal, but fine since color is set once)
- I would also prefer to have some default colors which already look good along with setting custom color. So it's easy to pick one from preselected which already look good. We could start with colors same as trello labels.

This is example from google calendar:
![image](https://cloud.githubusercontent.com/assets/831942/6880343/d4f03b02-d53c-11e4-9a58-fabf83434346.png)

In the beginning I thought custom color for ID is stupid idea, but now I like it, it helps differentiate ID from title. Will definitely use it once it's out.

**Comment by dewyze** [comment]
I added the bold feature and color selector, for now I did not add premade colors. I was trying to avoid jquery (both for personal experience and all it brings with that this doesn't need). Feel free to add a PR if you can find a good js color picker with that option. Otherwise, it is published and sent, enjoy!

**Comment by antulik** [comment]
👍 great work
